apiVersion: gcpserviceaccount.spacelift.upbound.io/v1alpha1
kind: GcpServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: gcpserviceaccount/v1alpha1/gcpserviceaccount
  labels:
    testing.upbound.io/example-name: k8s-core
  name: k8s-core
spec:
  forProvider:
    stackIdSelector:
      matchLabels:
        testing.upbound.io/example-name: k8s-core
    tokenScopes:
    - https://www.googleapis.com/auth/compute
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/devstorage.full_control

---

apiVersion: stack.spacelift.upbound.io/v1alpha1
kind: Stack
metadata:
  annotations:
    meta.upbound.io/example-id: gcpserviceaccount/v1alpha1/gcpserviceaccount
  labels:
    testing.upbound.io/example-name: k8s-core
  name: k8s-core
spec:
  forProvider:
    branch: master
    name: Kubernetes core services
    repository: core-infra
