apiVersion: gcpserviceaccount.spacelift.upbound.io/v1alpha1
kind: GcpServiceAccount 
metadata:
  annotations:
    meta.upbound.io/example-id: gcpserviceaccount/v1alpha1/gcpserviceaccount
  labels:
    testing.upbound.io/example-name: example-gcpserviceaccount
  name: example-gcpserviceaccount
spec:
  forProvider:
    tokenScopes:
      - https://www.googleapis.com/auth/compute
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/ndev.clouddns.readwrite
      - https://www.googleapis.com/auth/devstorage.full_control
      - https://www.googleapis.com/auth/userinfo.email
    stackIdRef:
      name: example-stack
