# reference https://github.com/coopnorge/cloud-platform-apis/blob/main/cloud-platform-apis/templates/repositoryconfig.github.coop.no/definition.yaml
apiVersion: github.coop.no/v1alpha1
kind: RepositoryConfig
metadata:
  name: repository-config
spec:
  description: Public Crossplane provider for Spacelift maintained by coopnorge
  branches:
    default: main
    protection:
      - id: main
        pattern: main
  pullRequests:
    deleteBranchOnMerge: true # delete regular branches after PR merge