apiVersion: environmentvariable.spacelift.upbound.io/v1alpha1
kind: EnvironmentVariable 
metadata:
  annotations:
    meta.upbound.io/example-id: environmentvariable/v1alpha1/environmentvariable
  labels:
    testing.upbound.io/example-name: exampleenvironmentvariable
  name: exampleenvironmentvariable
spec:
  forProvider:
    name: exampleenvironmentvariable
    valueSecretRef:
      key: example
      name: exampleenvsecret
      namespace: default
    writeOnly: false
    contextIdRef: 
      name: example-context
--- 
apiVersion: v1
kind: Secret
metadata:
  name: exampleenvsecret
stringData:
  example: bababooey