apiVersion: stack.spacelift.upbound.io/v1alpha1
kind: Space
metadata:
  annotations:
    meta.upbound.io/example-id: space/v1alpha1/space
  labels:
    testing.upbound.io/example-name: example-space
  name: example-space
spec:
  forProvider:
    name: example-space
    parentSpaceId: root
